// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywJMD4SPa1d-Pq-GaKHMwnmYJ_0jsQzM',
    appId: '1:410193263253:web:fc92c73db844ea3397799c',
    messagingSenderId: '410193263253',
    projectId: 'flutterproject-fe254',
    authDomain: 'flutterproject-fe254.firebaseapp.com',
    storageBucket: 'flutterproject-fe254.firebasestorage.app',
    measurementId: 'G-E70ELY1X4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03NGW_QgpEbR9CxOCFYuKnr0zMr_6m20',
    appId: '1:410193263253:android:f6f203302c7a77c497799c',
    messagingSenderId: '410193263253',
    projectId: 'flutterproject-fe254',
    storageBucket: 'flutterproject-fe254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXNQx1gM1YUUhz3GkV5S60xXks5SvXMs',
    appId: '1:410193263253:ios:b1ada52bd63519a097799c',
    messagingSenderId: '410193263253',
    projectId: 'flutterproject-fe254',
    storageBucket: 'flutterproject-fe254.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXNQx1gM1YUUhz3GkV5S60xXks5SvXMs',
    appId: '1:410193263253:ios:b1ada52bd63519a097799c',
    messagingSenderId: '410193263253',
    projectId: 'flutterproject-fe254',
    storageBucket: 'flutterproject-fe254.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBywJMD4SPa1d-Pq-GaKHMwnmYJ_0jsQzM',
    appId: '1:410193263253:web:bdcd9b6481d108e197799c',
    messagingSenderId: '410193263253',
    projectId: 'flutterproject-fe254',
    authDomain: 'flutterproject-fe254.firebaseapp.com',
    storageBucket: 'flutterproject-fe254.firebasestorage.app',
    measurementId: 'G-KGG8VVPSF9',
  );
}
